---
- name: set up ssh for push mode on the target machine
  ansible.builtin.include_tasks: sshserver.yml
  when: zfs_autobackup_mode == "push"

- name: set up ssh for pull mode on the target machine
  ansible.builtin.include_tasks: sshclient.yml
  when: zfs_autobackup_mode == "pull"

- name: create the target dataset
  community.general.zfs:
    name: "{{ zfs_autobackup_target_dataset }}"
    state: present
    extra_zfs_properties:
      readonly: "on"

- name: give zfs permissions to the zfs-autobackup user
  community.general.zfs_delegate_admin:
    name: "{{ zfs_autobackup_target_dataset }}"
    users: "{{ zfs_autobackup_user }}"
    permissions: "{{ zfs_autobackup_target_permissions }}"
