---
- name: install helper packages
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - mbuffer

- name: create a restricted service account
  ansible.builtin.user:
    name: "{{ zfs_autobackup_user }}"
    home: /usr/local/lib/zfs-autobackup
    system: true
    shell: "{{ lookup('ansible.builtin.pipe', 'which rbash') }}"

- name: create the rbash shell profile with restricted env
  ansible.builtin.copy:
    dest: /usr/local/lib/zfs-autobackup/.bash_profile
    owner: root
    mode: 0644
    content: |
      PATH="$HOME/bin"
      export PATH

- name: create the bin directory
  ansible.builtin.file:
    path: /usr/local/lib/zfs-autobackup/bin
    state: directory
    owner: root
    mode: 0755

- name: create symlinks for the binaries that zfs-autobackup is allowed to run
  ansible.builtin.file:
    path: "/usr/local/lib/zfs-autobackup/bin/{{ item }}"
    src: "{{ lookup('ansible.builtin.pipe', 'which %s' % item) }}"
    state: link
  loop:
    - zfs
    - mbuffer

- name: create the .ssh directory
  ansible.builtin.file:
    path: /usr/local/lib/zfs-autobackup/.ssh
    state: directory
    owner: "{{ zfs_autobackup_user }}"
    group: "{{ zfs_autobackup_user }}"
    mode: 0700

- name: set up zfs-autobackup on the source machine
  ansible.builtin.include_tasks: datasource.yml
  when: zfs_autobackup_role == "source"

- name: set up zfs-autobackup on the target machine
  ansible.builtin.include_tasks: datatarget.yml
  when: zfs_autobackup_role == "target"
