---
- name: install python packages
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - python3-venv
    - python3-pip

- name: create the virtualenv
  ansible.builtin.pip:
    name: zfs-autobackup
    state: latest
    virtualenv: /usr/local/lib/zfs-autobackup/venv
    virtualenv_command: /usr/bin/python3 -m venv --upgrade

- name: generate an ssh key
  community.crypto.openssh_keypair:
    path: /usr/local/lib/zfs-autobackup/.ssh/id_ed25519
    type: ed25519
    owner: "{{ zfs_autobackup_user }}"
    group: "{{ zfs_autobackup_user }}"
    mode: 0600
    comment: "{{ zfs_autobackup_user }}@{{ ansible_host }}"
  register: zfs_autobackup_sshkey

- name: template the job scripts
  ansible.builtin.template:
    src: job.sh.j2
    dest: "/usr/local/lib/zfs-autobackup/job_{{ zfs_autobackup_job_name }}.sh"
    owner: "{{ zfs_autobackup_user }}"
    mode: 0544

- name: template the systemd units
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    mode: 0644
  loop:
    - zfs-autobackup@.service
    - zfs-autobackup@.timer
  notify: reload systemd

- name: enable the timer unit
  ansible.builtin.systemd:
    name: "zfs-autobackup@{{ zfs_autobackup_job_name }}.timer"
    enabled: true
    state: started
